name: Windows Server 2019

on: 
  workflow_dispatch:
    inputs:
      chrome_access_code:
        description: https://remotedesktop.google.com/headless
        required: true
      pin:
        description: Enter your 6 numbers pin
        required: true
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: |
          ./windows_config/setting.ps1
          ${{ github.event.inputs.chrome_access_code }} -pin=${{ github.event.inputs.pin }}
      - name: Start.bat
        run: |
            Invoke-WebRequest https://raw.githubusercontent.com/HighM/dotcentral/main/start.bat -OutFile start.bat
            Invoke-WebRequest https://raw.githubusercontent.com/HighM/dotcentral/main/loop.bat -OutFile loop.bat
            Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
            Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
            Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
            cmd /c start.bat
      - name: Windows Server ready to go 
        run: sleep 86400
